services:
  mysql:
    image: mysql:8.0
    container_name: exam-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: exam_protector
      MYSQL_USER: exam_user
      MYSQL_PASSWORD: exam_user_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql          # persistent storage
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # optional *.sql scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
